---
language: ruby
cache: bundler
rvm:
  - 2.5.8
  - 2.6.6
  - 2.6.3
  - 2.7.1
  - ruby-head
before_install:
  - gem update --system
  - gem install bundler:1.17.3
  - gem install overcommit
script:
  - bundle exec rspec --order rand
  - overcommit --sign && overcommit --run
jobs:
  allow_failures:
    - rvm: ruby-head